dist: focal
language: perl

perl:
  - "blead"
  - "5.30"
  - "5.28"
  - "5.26"
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"

sudo: false

jobs:
  fast_finish: true
  include:
    - perl: 5.32
      env: COVERAGE=1 DDPTESTCOVERAGE=1
    # 5.12 and lower are not available on recent dists
    - perl: 5.10
      dist: trusty
    - perl: 5.12
      dist: trusy
  allow_failures:
    - perl: blead

before_install:
 - eval $(curl https://travis-perl.github.io/init) --auto
